# Generated by Django 2.2.4 on 2021-03-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='Actions',
        ),
    ]
